version: '3.8'
services:
  frontend:
    build:
      context: ./frontend2
    ports:
      - "3000:80"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend2
    ports:
      - "5000:5000"
